version: '3.8'

services:
  scrapy:
    build:
      context: ./flats_scraper
      dockerfile: dockerfile
    depends_on:
      - postgres
    command: sh -c "sleep 10 && scrapy crawl flats"  # Delay for PostgreSQL to start

  flask_app:
    build:
      context: ./flask_app
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - scrapy
      - postgres
    environment:
      - DATABASE_URL=postgresql://user_test:12345@postgres:5432/flats

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: flats
